author: Nevis Security AG
copyright: '© 2022 Nevis Security AG. All rights reserved.'
module: NevisExampleApp

clean: true
theme: fullwidth
output: Docs/generated
include: 'NevisExampleApp/*'
exclude: 'Pods/*'
skip_undocumented: true
hide_documentation_coverage: true
xcodebuild_arguments:
    - '-workspace'
    - 'NevisExampleApp.xcworkspace'
    - '-scheme'
    - 'NevisExampleApp'

custom_categories:
  - name: Application
    children:
      - AppDelegate
      - AppLoader
      - DependencyProvider
      - AppAssembly
  - name: Presentation / Coordinator
    children:
      - AppCoordinator
      - AppCoordinatorImpl
  - name: Presentation / Screens
    children:
      - Screen
      - ScreenViewModel
      - BaseScreen
      - LaunchScreen
      - LaunchViewModel
      - HomeScreen
      - HomeViewModel
      - QrScannerScreen
      - QrScannerViewModel
      - SelectAccountScreen
      - SelectAccountViewModel
      - SelectAccountParameter
      - SelectAccountItemViewModel
      - AccountCell
      - SelectAuthenticatorScreen
      - SelectAuthenticatorViewModel
      - SelectAuthenticatorParameter
      - SelectAuthenticatorItemViewModel
      - AuthenticatorCell
      - CredentialScreen
      - CredentialViewModel
      - CredentialParameter
      - PinParameter
      - PasswordParameter
      - CredentialProtectionInformation
      - AuthCloudApiRegistrationScreen
      - AuthCloudApiRegistrationViewModel
      - ChangeDeviceInformationScreen
      - ChangeDeviceInformationViewModel
      - ChangeDeviceInformationParameter
      - UsernamePasswordLoginScreen
      - UsernamePasswordLoginViewModel
      - TransactionConfirmationScreen
      - TransactionConfirmationViewModel
      - TransactionConfirmationParameter
      - ConfirmationScreen
      - ConfirmationViewModel
      - ConfirmationParameter
      - ResultScreen
      - ResultViewModel
      - ResultParameter
      - LoggingScreen
      - LoggingViewModel
  - name: Presentation / Utility
    children:
      - Authenticator
      - AuthenticatorAaid
      - PinAuthenticatorProtectionStatus
      - PasswordAuthenticatorProtectionStatus
      - ResponseObserver
      - ResponseObserverImpl
      - AuthCloudApiRegistrationValidator
      - JWTValidator
      - ValidationError
      - ValidationResult
      - OutlinedButton
      - Style
      - NSLabel
      - NSTextField
      - L10n
      - InteractionCountDownTimer
      - ObservableType
      - Reactive
      - SharedSequenceConvertibleType
      - Result
      - String?
      - UINavigationController
      - UIStackView
      - UIView
  - name: Domain / Nevis
    children:
      - PinChangerImpl
      - PinEnrollerImpl
      - PasswordChangerImpl
      - PasswordEnrollerImpl
      - PasswordPolicyImpl
      - AccountSelectorImpl
      - AuthenticatorSelectorImpl
      - AuthenticationAuthenticatorSelectorName
      - RegistrationAuthenticatorSelectorName
      - PinUserVerifierImpl
      - PasswordUserVerifierImpl
      - BiometricUserVerifierImpl
      - DevicePasscodeUserVerifierImpl
      - AccountValidator
      - AccountValidatorImpl
      - AuthenticatorValidator
      - AuthenticatorValidatorImpl
  - name: Domain / Model
    children:
      - AuthenticatorItem
      - Operation
      - OperationError
      - BusinessError
      - Credentials
      - OperationResponse
      - ChangePinResponse
      - ChangePasswordResponse
      - CompletedResponse
      - ConfirmTransactionResponse
      - EnrollPinResponse
      - EnrollPasswordResponse
      - SelectAccountResponse
      - SelectAuthenticatorResponse
      - VerifyPinResponse      
      - VerifyPasswordResponse
      - VerifyBiometricResponse
      - VerifyDevicePasscodeResponse
  - name: Domain / Repository
    children:
      - LoginRepository
  - name: Domain / Use Case
    children:
      - AuthCloudApiRegistrationUseCase
      - AuthCloudApiRegistrationUseCaseImpl
      - ChangeDeviceInformationUseCase
      - ChangeDeviceInformationUseCaseImpl
      - ChangePinUseCase
      - ChangePinUseCaseImpl
      - ChangePasswordUseCase
      - ChangePasswordUseCaseImpl
      - CreateDeviceInformationUseCase
      - CreateDeviceInformationUseCaseImpl
      - DecodePayloadUseCase
      - DecodePayloadUseCaseImpl
      - DeregistrationUseCase
      - DeregistrationUseCaseImpl
      - GetAccountsUseCase
      - GetAccountsUseCaseImpl
      - GetAuthenticatorsUseCase
      - GetAuthenticatorsUseCaseImpl
      - GetDeviceInformationUseCase
      - GetDeviceInformationUseCaseImpl
      - InBandAuthenticationUseCase
      - InBandAuthenticationUseCaseImpl
      - InitClientUseCase
      - InitClientUseCaseImpl
      - LoginUseCase
      - LoginUseCaseImpl
      - OutOfBandOperationUseCase
      - OutOfBandOperationUseCaseImpl
      - RegistrationUseCase
      - RegistrationUseCaseImpl
      - DeleteAuthenticatorsUseCase
      - DeleteAuthenticatorsUseCaseImpl
  - name: Domain / Client Provider
    children:
      - ClientProvider
      - ClientProviderImpl
  - name: Domain / Response Emitter
    children:
      - ResponseEmitter
      - ResponseEmitterImpl
  - name: Data / Model
    children:
      - LoginRequest
      - LoginResponse
  - name: Data / Repository
    children:
      - LoginRepositoryImpl
  - name: Data / Data Source
    children:
      - LoginDataSource
      - LoginDataSourceImpl
      - LoginSessionDelegate
  - name: Common
    children:
      - LoginConfiguration
      - AppConfiguration
      - Environment
      - ConfigurationLoader
      - ConfigurationLoaderImpl
      - Coordinator
      - NavigationParameterizable
      - DeepLink
      - DeepLinkHandler
      - DeepLinkHandlerImpl
      - AppError
      - ErrorHandlerChain
      - ErrorHandlerChainImpl
      - ErrorHandler
      - GeneralErrorHandlerName
      - GeneralErrorHandler
      - NevisErrorHandlerName
      - NevisErrorHandler
      - OSLog
      - String
      - '[String: String]'
      - UIDevice
      - SDKLogger
      - SDKLoggerImpl
