##
## Fastlane configuration for the Nevis Mobile Authentication SDK Example App iOS Reactive application.
## See https://docs.fastlane.tools
##

default_platform(:ios)

display_name = "Nevis Mobile Authentication SDK Example App iOS Reactive"

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

def report_on_success(message)
	slack(
		message: "#{message}\nCheck build logs: #{ENV['CURRENT_BUILD_URL']}",
		slack_url: ENV['SLACK_WEBHOOK_URL']
	) if ENV['SLACK_WEBHOOK_URL']
end

def report_on_error(message, exception)
	slack(
		message: "#{message}\nCheck build logs: #{ENV['CURRENT_BUILD_URL']}",
		slack_url: ENV['SLACK_WEBHOOK_URL'],
		success: false,
		attachment_properties: {
			fields: [
				{
					title: "Error message",
					value: exception.to_s,
					short: false
				}
			]
		}
	) if ENV['SLACK_WEBHOOK_URL']
	UI.user_error!("#{exception}")
end

platform :ios do
	desc "Build the application"
	lane :main do
		begin
			build_number = ENV["BUILD_NUMBER"] || get_build_number()
			version = get_version_number()
			increment_build_number(build_number: build_number)

			UI.message("Building #{display_name} #{version} (#{build_number}) 📦")

			cocoapods()
			gym(
				workspace: "NevisExampleApp.xcworkspace",
				scheme: "NevisExampleApp",
				configuration: "Release",
				clean: true,
				skip_codesigning: true,
				skip_profile_detection: true,
				skip_package_dependencies_resolution: true,
				skip_archive: true,
				skip_package_ipa: true
			)

			add_git_tag(tag: "release/#{version}/#{build_number}", message: "[Fastlane] #{display_name} #{version} (#{build_number})")
			push_git_tags

			report_on_success("#{display_name} build is completed: #{version} (#{build_number}) ✅")
		rescue => exception
			report_on_error("#{display_name} build failed ❌", exception)
		end
	end

	desc "Build the application"
	lane :pr do
		cocoapods()
		gym(
			workspace: "NevisExampleApp.xcworkspace",
			scheme: "NevisExampleApp",
			configuration: "Release",
			clean: true,
			skip_codesigning: true,
			skip_profile_detection: true,
			skip_package_dependencies_resolution: true,
			skip_archive: true,
			skip_package_ipa: true
		)
	end
end
